### ISSUE TITLE
pupyx86.lin is missing

### ISSUE THREAD

**Issue by quentinhardy** [n1nj4sec/pupy#206] opened 2016-10-18 13:26 UTC
Hello,

**_pupyx86.lin_** is missing in the [https://github.com/n1nj4sec/pupy-binaries](https://github.com/n1nj4sec/pupy-binaries) project.

If you try to generate a _lin_x86_ payload, the following error will appear:

```
Traceback (most recent call last):
  File "pupygen.py", line 341, in <module>
    binary=get_edit_pupyx86_lin(conf)
  File "pupygen.py", line 37, in get_edit_pupyx86_lin
    return get_edit_binary(os.path.join(ROOT, "payload_templates","pupyx86.lin"), conf)
  File "pupygen.py", line 51, in get_edit_binary
    with open(path, 'rb') as f:
IOError: [Errno 2] **No such file or directory**: '/[...]/payload_templates/pupyx86.lin'
```

It will be very appreciate if the lin_x86 and lin_x64 binaries are compiled on a (very) old Linux for having an **old libc** linked from the binary. 

When I compile linux binaries, most of the time I use a CentOS 5.11 Virtual Machine for having an old libc version (**2.5 in my case**). _ldd --version_  command can be used to check the libc version used by the system.

Of course, if linux binaires are not compiled with an old libc version, binaires will not run on Linux systems using an old libc (e.g. some RedHat versions).

Thank you very much in advance for your help,

**Comment by alxchk** [comment] 2016-10-21 04:52
You can try to use one from my repo - https://github.com/alxchk/pupy-binaries.
Also if you have issues with linux loader - write to my tracker (https://github.com/alxchk/pupy)

**Comment by ChristopherShawn** [comment] 2017-05-02 20:47
Would this be caused by a build script error?  It doesn't seem to be creating the .lin or .so files, and my linux_x86.zip files grow to ~2GB when building new payloads

**Comment by n1nj4sec** [comment] 2017-05-21 10:43
wow it shouldn't go over 10MB ! try to unzip them to understand what is happening. I close this issue but you can open a new one if your problem persist

**Closed by n1nj4sec** 2017-05-21 10:43 UTC
Labels: TODO
